name: OpenSSF scorecard check

on:
  schedule:
    # Run at 6:00am on Mondays
    - cron: '0 6 * * 1'

permissions:
    contents: read

jobs:
  PerformOSSFScan:
    name: Perform OpenSSF Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
            persist-credentials: false
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
          publish: false