name: OpenSSF scorecard check

on:
  schedule:
    # Run at 6:00am on Mondays
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
    contents: read

jobs:
  PerformOSSFScan:
    name: Perform OpenSSF Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: "Upload artifact"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: OpenSSF Scorecard SARIF file
          path: results.sarif
          retention-days: 5